### ISSUE TITLE
Image is clipping pixels on some fonts

### ISSUE THREAD

**Issue by mikemclin** [vincent7128/text-image#3]
When I implemented the text-image and applied the [Dancing Script](https://fonts.google.com/specimen/Dancing+Script) Google Font, the text was getting clipped.

Perhaps adding a "whitespace buffer" setting (for each side) would allow people to fix this manually?

<img width="333" alt="screen shot 2017-11-11 at 5 41 53 pm" src="https://user-images.githubusercontent.com/1570155/32694198-1bc17d4c-c708-11e7-810c-e3f5837b5628.png">

**Comment by vincent7128** [comment]
I removed the default message trim function, now you can add whitespace before or after with the message.

**Comment by mikemclin** [comment]
Perfect, thanks

**Comment by mikemclin** [comment]
This still isn't working.  I have wrapped both sides of the string being passed into the function with a space character.  I also tried using `&nbsp;` characters thinking maybe that would do the trick, but it just dumped out the actual entity string, instead of the actual non-breaking space character.

**Comment by vincent7128** [comment]
Did you have updated to the last version (0.5.1)?

**Comment by mikemclin** [comment]
Yes.  I also checked the source code to make sure that the `trim` method was removed from the package code.

**Comment by vincent7128** [comment]
I try on my demo page (https://vincent7128.github.io/text-image/), it works.
![cbaa7326-681b-4aaf-88a5-1159ecaed057](https://user-images.githubusercontent.com/31979452/32849126-476c6920-ca69-11e7-9683-1bf730d512d2.png)

**Comment by vincent7128** [comment]
Can you show me your code? What is your browser?

**Comment by mikemclin** [comment]
I am sorry.  I was implementing this in React, and I think maybe my HMR was screwing up.  I can confirm that the issue was on my end, and the code works as expected.  Thank you.

**Comment by mikemclin** [comment]
I just noticed the crop is also happening on the bottom.  I implemented in your demo to verify.

<img width="731" alt="screen shot 2017-11-26 at 7 21 47 pm" src="https://user-images.githubusercontent.com/1570155/33246148-3b67e5ae-d2df-11e7-8cf1-8e0cb883644a.png">

**Comment by mikemclin** [comment]
The ability to change the `line-height` style would solve this issue.  Currently it is hardcoded to `1`.  I've tried several handwritten fonts, and all of them seem to clip at the bottom.

**Comment by vincent7128** [comment]
I see, Maybe I can add option line-height to constructor.

**Comment by vincent7128** [comment]
Hi @mikemclin ,
Thank's your help, I just update the version add the lineHeight property to the style option.
And I also change the default line height to 1.2em, it can fix the clip at the bottom bug.

![screen shot 2017-11-27 at 15 26 52](https://user-images.githubusercontent.com/31979452/33255535-0fba0d74-d389-11e7-85d4-d488d2bc4141.png)
