### ISSUE TITLE
own text style (help)

### ISSUE THREAD

**Issue by Dark3n89** [vincent7128/text-image#7]
Hi thank you for a great project, could you advise me how I can add my own fonts when I have downloaded .TTF files? Thank you

I try to use a font that the machine will not be able to read (eg facebook, google)

**Comment by vincent7128** [comment]
> I try to use a font that the machine will not be able to read

"the machine" is client browser? Right?

**Comment by Dark3n89** [comment]
> "the machine" is client browser? Right?

machine, I think of tools that can extract text from a picture, social networks etc: facebook will give you a penalty when translated, I know fonts that cannot be translated, for example (photo) means HELLO in my language and google is unable to identify the text.

https://ibb.co/1KDBCr9

**Comment by vincent7128** [comment]
You mean the image can not OCR, Right?

**Comment by Dark3n89** [comment]
> You mean the image can not OCR, Right?

I know it can't, I experimented with different font styles and my language has diacritics (č,ř,š,ž) just need to get it to the page.

**Comment by Dark3n89** [comment]
oooh  im idiot, sorry for waste time  i write bad phrase: 

@font-face {
    font-family: dark;
    src: url("dkn.ttf") 
}
